import {
  AlertCircle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Bell,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarOff,
  CalendarPlus,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  Clock,
  Cloud,
  Copy,
  Download,
  ExternalLink,
  Eye,
  Info,
  Loader2,
  Menu,
  Minus,
  Moon,
  MoreHorizontal,
  Pencil,
  Plus,
  RefreshCw,
  RotateCw,
  Search,
  Settings,
  ShieldCheck,
  ShieldMinus,
  Sun,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  UserPlus,
  UserX,
  Users,
  Video,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * The icon registry — the serializable form of `Icon`.
 *
 * `Icon`'s `icon` prop is a React component, so it cannot survive JSON. A string
 * `name` keyed into this registry can, which is what lets an icon be chosen from
 * config, content, or any other data-driven source rather than only in code.
 *
 * Curated from the icons the app + design system genuinely use — not the whole
 * lucide set, which would be thousands of glyphs in the bundle. Add a glyph here
 * to make it available by name.
 */
export const ICONS = {
  'alert-circle': AlertCircle,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-down': ArrowUpDown,
  bell: Bell,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  'calendar-clock': CalendarClock,
  'calendar-days': CalendarDays,
  'calendar-off': CalendarOff,
  'calendar-plus': CalendarPlus,
  check: Check,
  'check-all': CheckCheck,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-up-down': ChevronsUpDown,
  circle: Circle,
  clock: Clock,
  cloud: Cloud,
  copy: Copy,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  info: Info,
  loader: Loader2,
  menu: Menu,
  minus: Minus,
  moon: Moon,
  'more-horizontal': MoreHorizontal,
  pencil: Pencil,
  plus: Plus,
  refresh: RefreshCw,
  rotate: RotateCw,
  search: Search,
  settings: Settings,
  'shield-check': ShieldCheck,
  'shield-minus': ShieldMinus,
  sun: Sun,
  trash: Trash2,
  'triangle-alert': TriangleAlert,
  upload: Upload,
  user: User,
  'user-plus': UserPlus,
  'user-x': UserX,
  users: Users,
  video: Video,
  x: X,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

/** Sorted names — the option list for the `name` control. */
export const ICON_NAMES = Object.keys(ICONS).sort() as IconName[];
