// This file is auto-generated by @hey-api/openapi-ts

/**
 * The access token.
 *
 */
export type AccessToken = string;

/**
 * Configuration of the Django `allauth.account` app.
 *
 */
export type AccountConfiguration = {
    email_verification_by_code_enabled: boolean;
    is_open_for_signup: boolean;
    login_by_code_enabled: boolean;
    login_methods?: Array<'email' | 'username'>;
    password_reset_by_code_enabled?: boolean;
};

export type Authenticated = {
    /**
     * A list of methods used to authenticate.
     *
     */
    methods: Array<AuthenticationMethod>;
    user: User;
};

export type AuthenticatedMeta = BaseAuthenticationMeta & {
    is_authenticated: true;
};

export type AuthenticatedResponse = {
    data: Authenticated;
    meta: AuthenticationMeta;
    status: StatusOk;
};

export type AuthenticationMeta = BaseAuthenticationMeta & {
    is_authenticated: boolean;
};

export type AuthenticationMethod = {
    at: Timestamp;
    email?: Email;
    method: 'password';
    username?: Username;
} | {
    at: Timestamp;
    email: Email;
    method: 'password_reset';
} | {
    at: Timestamp;
    email: Email;
    method: 'code';
} | {
    at: Timestamp;
    method: 'code';
    phone: Phone;
} | {
    at: Timestamp;
    method: 'password';
    reauthenticated: true;
} | {
    at: Timestamp;
    method: 'socialaccount';
    provider: ProviderId;
    uid: ProviderAccountId;
} | {
    at: Timestamp;
    method: 'mfa';
    reauthenticated?: boolean;
    type: AuthenticatorType;
};

/**
 * An authentication related response.
 *
 */
export type AuthenticationResponse = {
    data: {
        flows: Array<Flow>;
    };
    meta: AuthenticationMeta;
    status: 401;
};

/**
 * An authenticator code.
 *
 */
export type AuthenticatorCode = string;

/**
 * Authenticator ID.
 *
 */
export type AuthenticatorId = number;

export type AuthenticatorList = Array<TotpAuthenticator | RecoveryCodesAuthenticator | WebAuthnAuthenticator>;

/**
 * The type of authenticator.
 *
 */
export type AuthenticatorType = 'recovery_codes' | 'totp' | 'webauthn';

export type BaseAuthenticationMeta = {
    /**
     * The access token (`app` clients only).
     *
     */
    access_token?: string;
    /**
     * The session token (`app` clients only).
     *
     */
    session_token?: string;
    /**
     * The refresh token (`app` clients only).
     *
     * MANUAL PATCH: present at runtime but NOT declared in the OpenAPI schema.
     * Re-apply after regenerating the client (see openapi-ts-auth script).
     */
    refresh_token?: string;
};

export type BaseAuthenticator = {
    created_at: Timestamp;
    last_used_at: OptionalTimestamp;
};

export type BaseSignup = {
    email: Email;
    first_name: string;
    last_name: string;
    phone: Phone;
};

/**
 * The client ID (in case of OAuth2 or OpenID Connect based providers)
 *
 */
export type ClientId = string;

/**
 * An one-time code.
 *
 */
export type Code = string;

export type ConfigurationResponse = {
    data: {
        account: AccountConfiguration;
        mfa?: MfaConfiguration;
        socialaccount?: SocialAccountConfiguration;
        usersessions?: UserSessionsConfiguration;
    };
    status: StatusOk;
};

export type ConfirmLoginCode = {
    code: Code;
};

export type ConflictResponse = {
    status: 409;
};

/**
 * The email address.
 *
 */
export type Email = string;

export type EmailAddress = {
    email: Email;
    primary: boolean;
    verified: boolean;
};

export type EmailVerificationInfo = {
    data: {
        email: Email;
        user: User;
    };
    meta: {
        is_authenticating: boolean;
    };
    status: StatusOk;
};

export type EndSessions = {
    /**
     * The IDs of the sessions that are to be ended.
     *
     */
    sessions: Array<number>;
};

export type ErrorResponse = {
    errors?: Array<{
        /**
         * An error code.
         *
         */
        code: string;
        /**
         * A human readable error message.
         *
         */
        message: string;
        /**
         * The name of the input parameter that was incorrect.
         *
         */
        param?: string;
    }>;
    status?: 400;
};

export type Flow = {
    id: 'login' | 'login_by_code' | 'mfa_authenticate' | 'mfa_reauthenticate' | 'provider_redirect' | 'provider_signup' | 'provider_token' | 'reauthenticate' | 'signup' | 'verify_email' | 'verify_phone';
    is_pending?: true;
    provider?: Provider;
    /**
     * Matches `settings.MFA_SUPPORTED_TYPES`.
     */
    types?: Array<AuthenticatorType>;
};

export type ForbiddenResponse = {
    status: 403;
};

export type Login = {
    password: Password;
} & ({
    username: Username;
} | {
    email: Email;
} | {
    phone: Phone;
});

export type MfaAuthenticate = {
    code: AuthenticatorCode;
};

/**
 * Configuration of the Django `allauth.mfa` app.
 *
 */
export type MfaConfiguration = {
    /**
     * Matches `settings.MFA_SUPPORTED_TYPES`.
     *
     */
    supported_types: Array<AuthenticatorType>;
};

export type MfaTrust = {
    trust: boolean;
};

export type OptionalTimestamp = Timestamp;

export type PasskeySignup = BaseSignup;

/**
 * The password.
 *
 */
export type Password = string;

/**
 * The phone number.
 *
 */
export type Phone = string;

/**
 * A phone number.
 *
 */
export type PhoneNumber = {
    phone: string;
    verified: boolean;
};

export type PhoneNumberChangeResponse = {
    data: Array<PhoneNumber>;
    status: StatusAccepted;
};

export type PhoneNumbersResponse = {
    data: Array<PhoneNumber>;
    status: StatusOk;
};

/**
 * The process to be executed when the user successfully
 * authenticates. When set to `login`, the user will be logged into the
 * account to which the provider account is connected, or if no such
 * account exists, a signup will occur. If set to `connect`, the provider
 * account will be connected to the list of provider accounts for the
 * currently authenticated user.
 *
 */
export type Process = 'login' | 'connect';

export type Provider = {
    /**
     * The client ID (in case of OAuth2 or OpenID Connect based providers)
     *
     */
    client_id?: string;
    /**
     * The authentication flows the provider integration supports.
     *
     */
    flows: Array<'provider_redirect' | 'provider_token'>;
    /**
     * The provider ID.
     *
     */
    id: string;
    /**
     * The name of the provider.
     *
     */
    name: string;
    /**
     * The OIDC discovery or well-known URL (in case of OAuth2 or OpenID Connect based providers)
     *
     */
    openid_configuration_url?: string;
};

export type ProviderAccount = {
    /**
     * A name derived from the third-party provider account data.
     *
     */
    display: string;
    provider: Provider;
    uid: ProviderAccountId;
};

/**
 * The provider specific account ID.
 *
 */
export type ProviderAccountId = string;

/**
 * The provider ID.
 *
 */
export type ProviderId = string;

export type ProviderList = Array<Provider>;

export type ProviderRedirect = {
    /**
     * The URL to return to after the redirect flow is complete.
     *
     * Note that this is not to be mistaken with the callback URL that you
     * configure over at the OAuth provider during the OAuth app/client
     * setup. The flow is as follows:
     *
     * 1. Your frontend redirects to the headless provider redirect
     * endpoint in a synchronous (non-XHR) manner, informing allauth
     * (by means of `callback_url`) where to redirect to after the
     * provider handshake is completed.
     *
     * 2. Headless will redirect to the (OAuth) identity provider to
     * initiate the handshake, passing along a different callback URL
     * to the provider: one that points to an allauth backend URL.
     * This is the URL that you need to have setup at your OAuth
     * app/client configuration. Note that this must be a backend URL
     * as providers can use POST requests to perform their callbacks,
     * which is something a frontend would not be able to handle.
     *
     * 3. After the authorization at the provider is completed, the
     * provider redirects to the *backend* allauth callback URL, which
     * will then redirect back to the *frontend* callback URL.
     *
     * 4. Your frontend is now expected to fetch the current session to
     * determine what the next course of action is. The user could be
     * authenticated at this point, or another flow is pending
     * (e.g. email verification, or, provider signup). In case of
     * errors a `?error=` is passed to the frontend callback URL.
     *
     */
    callback_url: string;
    process: Process;
    provider: ProviderId;
};

export type ProviderSignup = BaseSignup;

export type ProviderToken = {
    process: Process;
    provider: ProviderId;
    /**
     * The token.
     *
     */
    token: {
        /**
         * The access token.
         *
         */
        access_token?: string;
        client_id: ClientId;
        /**
         * The ID token.
         *
         */
        id_token?: string;
    };
};

export type Reauthenticate = {
    password: Password;
};

export type ReauthenticationRequired = {
    flows: Array<Flow>;
    /**
     * A list of methods used to authenticate.
     *
     */
    methods: Array<AuthenticationMethod>;
    user: User;
};

/**
 * A response indicating reauthentication is required.
 *
 */
export type ReauthenticationResponse = {
    data: ReauthenticationRequired;
    meta: AuthenticatedMeta;
    status: 401;
};

export type RecoveryCodesAuthenticator = BaseAuthenticator & {
    /**
     * The total number of recovery codes that initially were available.
     *
     */
    total_code_count: number;
    /**
     * The authenticator type.
     *
     */
    type: 'recovery_codes';
    /**
     * The number of recovery codes that are unused.
     *
     */
    unused_code_count: number;
};

/**
 * The refresh token.
 *
 */
export type RefreshToken = string;

export type RequestLoginCode = {
    phone: Phone;
} | {
    email: Email;
};

export type RequestPassword = {
    email: Email;
};

export type ResetPassword = {
    /**
     * The password reset key
     */
    key: string;
    password: Password;
};

export type SensitiveRecoveryCodesAuthenticator = RecoveryCodesAuthenticator & {
    /**
     * The list of unused codes.
     *
     */
    unused_codes: Array<AuthenticatorCode>;
};

export type Session = {
    created_at: Timestamp;
    id: number;
    ip: string;
    is_current: boolean;
    last_seen_at?: Timestamp;
    user_agent: string;
};

/**
 * The session is expired or invalid.
 *
 */
export type SessionGoneResponse = {
    data: {
        [key: string]: unknown;
    };
    meta: AuthenticationMeta;
    status: 410;
};

export type Signup = BaseSignup & {
    password?: Password;
};

/**
 * Configuration of the Django `allauth.socialaccount` app.
 *
 */
export type SocialAccountConfiguration = {
    providers: ProviderList;
};

export type StatusAccepted = 202;

export type StatusOk = 200;

export type TotpAuthenticator = BaseAuthenticator & {
    type: 'totp';
};

/**
 * An epoch based timestamp (trivial to parse using: `new Date(value)*1000`)
 *
 */
export type Timestamp = number;

export type User = {
    /**
     * The display name for the user.
     */
    display: string;
    /**
     * The email address.
     */
    email?: string;
    /**
     * Whether or not the account has a password set.
     */
    has_usable_password: boolean;
    /**
     * The user ID.
     */
    id?: number;
    /**
     * The username.
     */
    username: string;
};

/**
 * Configuration of the Django `allauth.usersessions` app.
 *
 */
export type UserSessionsConfiguration = {
    /**
     * Matches `settings.USERSESSIONS_TRACK_ACTIVITY`.
     *
     */
    track_activity: boolean;
};

/**
 * The username.
 *
 */
export type Username = string;

export type VerifyEmail = {
    /**
     * The email verification key
     */
    key: string;
};

export type VerifyPhone = {
    /**
     * The phone verification code
     */
    code: string;
};

export type WebAuthnAuthenticator = BaseAuthenticator & {
    id: AuthenticatorId;
    /**
     * Whether or not this authenticator represents a passkey. Absent if it is not specified.
     *
     */
    is_passwordless?: boolean;
    name: string;
    type: 'webauthn';
};

export type WebAuthnCredential = {
    [key: string]: unknown;
};

export type WebAuthnCredentialCreationOptions = {
    creation_options: {
        [key: string]: unknown;
    };
};

export type WebAuthnCredentialRequestOptions = {
    request_options: {
        [key: string]: unknown;
    };
};

/**
 * The type of client accessing the API.
 */
export type Client = 'app' | 'browser';

/**
 * The email verification key
 */
export type EmailVerificationKey = string;

/**
 * When present (regardless of its value), enables passwordless sign-in via a WebAuthn credential (Passkey),
 * but may enforce additional multi-factor authentication (MFA) requirements. Omit the parameter to disable.
 *
 */
export type PasswordLess = boolean;

/**
 * The password reset key
 */
export type PasswordResetKey = string;

/**
 * Session token. Only needed when `client` is equal to `app`.
 *
 */
export type SessionToken = string;

export type AddWebAuthnAuthenticator = {
    credential: WebAuthnCredential;
    name?: string;
};

/**
 * Authenticate using WebAuthn.
 */
export type AuthenticateWebAuthn = {
    credential: WebAuthnCredential;
};

export type ChangePassword = {
    current_password?: Password;
    /**
     * The current password.
     *
     */
    new_password: string;
};

export type ConfirmLoginCode2 = ConfirmLoginCode;

export type DeleteWebAuthn = {
    /**
     * The IDs of the authenticator that are to be deleted.
     *
     */
    authenticators: Array<AuthenticatorId>;
};

export type Email2 = {
    email: Email;
};

export type EndSessions2 = EndSessions;

export type Login2 = Login;

/**
 * Login using WebAuthn.
 */
export type LoginWebAuthn = {
    credential: WebAuthnCredential;
};

export type MfaAuthenticate2 = MfaAuthenticate;

export type MfaTrust2 = MfaTrust;

export type MarkPrimaryEmail = {
    /**
     * An email address.
     *
     */
    email: string;
    /**
     * Primary flag.
     *
     */
    primary: true;
};

export type PasskeySignup2 = PasskeySignup;

export type Phone2 = {
    phone: string;
};

export type ProviderAccount2 = {
    account: ProviderAccountId;
    provider: ProviderId;
};

export type ProviderRedirect2 = ProviderRedirect;

export type ProviderSignup2 = ProviderSignup;

export type ProviderToken2 = ProviderToken;

export type Reauthenticate2 = Reauthenticate;

/**
 * Reauthenticate using WebAuthn.
 */
export type ReauthenticateWebAuthn = {
    credential: WebAuthnCredential;
};

export type RefreshToken2 = {
    refresh_token: RefreshToken;
};

export type RequestLoginCode2 = RequestLoginCode;

export type RequestPassword2 = RequestPassword;

export type ResetPassword2 = ResetPassword;

export type SetupTotp = {
    code: AuthenticatorCode;
};

export type Signup2 = Signup;

export type UpdateWebAuthn = {
    id?: AuthenticatorId;
    name?: string;
};

export type VerifyEmail2 = VerifyEmail;

export type VerifyPhone2 = VerifyPhone;

export type PostAuthAppV1TokensRefreshData = {
    body?: RefreshToken2;
    path?: never;
    query?: never;
    url: '/auth/app/v1/tokens/refresh';
};

export type PostAuthAppV1TokensRefreshErrors = {
    /**
     * The refresh token is invalid or expired.
     */
    400: ErrorResponse;
};

export type PostAuthAppV1TokensRefreshError = PostAuthAppV1TokensRefreshErrors[keyof PostAuthAppV1TokensRefreshErrors];

export type PostAuthAppV1TokensRefreshResponses = {
    /**
     * A new access token (and optionally new refresh token).
     */
    200: {
        data: {
            access_token: AccessToken;
            refresh_token?: RefreshToken;
        };
        status: StatusOk;
    };
};

export type PostAuthAppV1TokensRefreshResponse = PostAuthAppV1TokensRefreshResponses[keyof PostAuthAppV1TokensRefreshResponses];

export type PostAuthBrowserV1AuthProviderRedirectData = {
    /**
     * Initiate the provider redirect flow.
     *
     */
    body: ProviderRedirect2;
    path?: never;
    query?: never;
    url: '/auth/browser/v1/auth/provider/redirect';
};

export type GetAuthByClientV1AccountAuthenticatorsData = {
    body?: never;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/account/authenticators';
};

export type GetAuthByClientV1AccountAuthenticatorsErrors = {
    /**
     * Not authenticated.
     */
    401: AuthenticationResponse;
    /**
     * The response indicates session is invalid or no longer exists.
     *
     */
    410: SessionGoneResponse;
};

export type GetAuthByClientV1AccountAuthenticatorsError = GetAuthByClientV1AccountAuthenticatorsErrors[keyof GetAuthByClientV1AccountAuthenticatorsErrors];

export type GetAuthByClientV1AccountAuthenticatorsResponses = {
    /**
     * List of authenticators.
     *
     */
    200: {
        data: AuthenticatorList;
        status: StatusOk;
    };
};

export type GetAuthByClientV1AccountAuthenticatorsResponse = GetAuthByClientV1AccountAuthenticatorsResponses[keyof GetAuthByClientV1AccountAuthenticatorsResponses];

export type GetAuthByClientV1AccountAuthenticatorsRecoveryCodesData = {
    body?: never;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/account/authenticators/recovery-codes';
};

export type GetAuthByClientV1AccountAuthenticatorsRecoveryCodesErrors = {
    /**
     * The response indicates reauthentication is required.
     *
     */
    401: ReauthenticationResponse;
    /**
     * Not found.
     *
     */
    404: {
        status: 404;
    };
};

export type GetAuthByClientV1AccountAuthenticatorsRecoveryCodesError = GetAuthByClientV1AccountAuthenticatorsRecoveryCodesErrors[keyof GetAuthByClientV1AccountAuthenticatorsRecoveryCodesErrors];

export type GetAuthByClientV1AccountAuthenticatorsRecoveryCodesResponses = {
    /**
     * Information on the recovery codes.
     *
     */
    200: {
        data: SensitiveRecoveryCodesAuthenticator;
        status: StatusOk;
    };
};

export type GetAuthByClientV1AccountAuthenticatorsRecoveryCodesResponse = GetAuthByClientV1AccountAuthenticatorsRecoveryCodesResponses[keyof GetAuthByClientV1AccountAuthenticatorsRecoveryCodesResponses];

export type PostAuthByClientV1AccountAuthenticatorsRecoveryCodesData = {
    body?: never;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/account/authenticators/recovery-codes';
};

export type PostAuthByClientV1AccountAuthenticatorsRecoveryCodesErrors = {
    /**
     * An input error occurred.
     */
    400: ErrorResponse;
    /**
     * The response indicates reauthentication is required.
     *
     */
    401: ReauthenticationResponse;
};

export type PostAuthByClientV1AccountAuthenticatorsRecoveryCodesError = PostAuthByClientV1AccountAuthenticatorsRecoveryCodesErrors[keyof PostAuthByClientV1AccountAuthenticatorsRecoveryCodesErrors];

export type DeleteAuthByClientV1AccountAuthenticatorsTotpData = {
    body?: never;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/account/authenticators/totp';
};

export type DeleteAuthByClientV1AccountAuthenticatorsTotpErrors = {
    /**
     * The response indicates reauthentication is required.
     *
     */
    401: ReauthenticationResponse;
};

export type DeleteAuthByClientV1AccountAuthenticatorsTotpError = DeleteAuthByClientV1AccountAuthenticatorsTotpErrors[keyof DeleteAuthByClientV1AccountAuthenticatorsTotpErrors];

export type DeleteAuthByClientV1AccountAuthenticatorsTotpResponses = {
    /**
     * A success response.
     *
     */
    200: {
        status: StatusOk;
    };
};

export type DeleteAuthByClientV1AccountAuthenticatorsTotpResponse = DeleteAuthByClientV1AccountAuthenticatorsTotpResponses[keyof DeleteAuthByClientV1AccountAuthenticatorsTotpResponses];

export type GetAuthByClientV1AccountAuthenticatorsTotpData = {
    body?: never;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/account/authenticators/totp';
};

export type GetAuthByClientV1AccountAuthenticatorsTotpErrors = {
    /**
     * No TOTP authenticator has been set up.
     *
     */
    404: {
        meta: {
            /**
             * A TOTP secret that can be used to setup a new authenticator.
             *
             */
            secret: string;
            /**
             * otpauth URI from which a QR code can be generated and scanned by OTP clients.
             *
             */
            totp_url: string;
        };
        status: 404;
    };
    /**
     * The account prohibits adding an authenticator, e.g. because of an unverified email address.
     *
     */
    409: ConflictResponse;
};

export type GetAuthByClientV1AccountAuthenticatorsTotpError = GetAuthByClientV1AccountAuthenticatorsTotpErrors[keyof GetAuthByClientV1AccountAuthenticatorsTotpErrors];

export type GetAuthByClientV1AccountAuthenticatorsTotpResponses = {
    /**
     * Information on the TOTP authenticator.
     *
     */
    200: {
        data: TotpAuthenticator;
        meta?: {
            /**
             * Whether or not recovery codes where generated automatically.
             */
            recovery_codes_generated?: boolean;
        };
        status: StatusOk;
    };
};

export type GetAuthByClientV1AccountAuthenticatorsTotpResponse = GetAuthByClientV1AccountAuthenticatorsTotpResponses[keyof GetAuthByClientV1AccountAuthenticatorsTotpResponses];

export type PostAuthByClientV1AccountAuthenticatorsTotpData = {
    body?: SetupTotp;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/account/authenticators/totp';
};

export type PostAuthByClientV1AccountAuthenticatorsTotpErrors = {
    /**
     * An input error occurred.
     */
    400: ErrorResponse;
    /**
     * The response indicates reauthentication is required.
     *
     */
    401: ReauthenticationResponse;
    /**
     * The account prohibits adding an authenticator, e.g. because of an unverified email address.
     *
     */
    409: ConflictResponse;
};

export type PostAuthByClientV1AccountAuthenticatorsTotpError = PostAuthByClientV1AccountAuthenticatorsTotpErrors[keyof PostAuthByClientV1AccountAuthenticatorsTotpErrors];

export type PostAuthByClientV1AccountAuthenticatorsTotpResponses = {
    /**
     * Information on the TOTP authenticator.
     *
     */
    200: {
        data: TotpAuthenticator;
        meta?: {
            /**
             * Whether or not recovery codes where generated automatically.
             */
            recovery_codes_generated?: boolean;
        };
        status: StatusOk;
    };
};

export type PostAuthByClientV1AccountAuthenticatorsTotpResponse = PostAuthByClientV1AccountAuthenticatorsTotpResponses[keyof PostAuthByClientV1AccountAuthenticatorsTotpResponses];

export type DeleteAuthByClientV1AccountEmailData = {
    body?: Email2;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/account/email';
};

export type DeleteAuthByClientV1AccountEmailErrors = {
    /**
     * An input error occurred.
     */
    400: ErrorResponse;
};

export type DeleteAuthByClientV1AccountEmailError = DeleteAuthByClientV1AccountEmailErrors[keyof DeleteAuthByClientV1AccountEmailErrors];

export type DeleteAuthByClientV1AccountEmailResponses = {
    /**
     * List of email addresses.
     *
     */
    200: {
        data: Array<EmailAddress>;
        status: StatusOk;
    };
};

export type DeleteAuthByClientV1AccountEmailResponse = DeleteAuthByClientV1AccountEmailResponses[keyof DeleteAuthByClientV1AccountEmailResponses];

export type GetAuthByClientV1AccountEmailData = {
    body?: never;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/account/email';
};

export type GetAuthByClientV1AccountEmailErrors = {
    /**
     * Not authenticated.
     */
    401: AuthenticationResponse;
};

export type GetAuthByClientV1AccountEmailError = GetAuthByClientV1AccountEmailErrors[keyof GetAuthByClientV1AccountEmailErrors];

export type GetAuthByClientV1AccountEmailResponses = {
    /**
     * List of email addresses.
     *
     */
    200: {
        data: Array<EmailAddress>;
        status: StatusOk;
    };
};

export type GetAuthByClientV1AccountEmailResponse = GetAuthByClientV1AccountEmailResponses[keyof GetAuthByClientV1AccountEmailResponses];

export type PatchAuthByClientV1AccountEmailData = {
    body?: MarkPrimaryEmail;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/account/email';
};

export type PatchAuthByClientV1AccountEmailErrors = {
    /**
     * An input error occurred.
     */
    400: ErrorResponse;
};

export type PatchAuthByClientV1AccountEmailError = PatchAuthByClientV1AccountEmailErrors[keyof PatchAuthByClientV1AccountEmailErrors];

export type PatchAuthByClientV1AccountEmailResponses = {
    /**
     * List of email addresses.
     *
     */
    200: {
        data: Array<EmailAddress>;
        status: StatusOk;
    };
};

export type PatchAuthByClientV1AccountEmailResponse = PatchAuthByClientV1AccountEmailResponses[keyof PatchAuthByClientV1AccountEmailResponses];

export type PostAuthByClientV1AccountEmailData = {
    body?: Email2;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/account/email';
};

export type PostAuthByClientV1AccountEmailErrors = {
    /**
     * An input error occurred.
     */
    400: ErrorResponse;
    /**
     * The response indicates authentication or re-authentication is required.
     *
     */
    401: AuthenticationResponse | ReauthenticationResponse;
    /**
     * Conflict. For example, when no user is authenticated and no email verification flow is pending.
     *
     */
    409: ConflictResponse;
};

export type PostAuthByClientV1AccountEmailError = PostAuthByClientV1AccountEmailErrors[keyof PostAuthByClientV1AccountEmailErrors];

export type PostAuthByClientV1AccountEmailResponses = {
    /**
     * List of email addresses.
     *
     */
    200: {
        data: Array<EmailAddress>;
        status: StatusOk;
    };
};

export type PostAuthByClientV1AccountEmailResponse = PostAuthByClientV1AccountEmailResponses[keyof PostAuthByClientV1AccountEmailResponses];

export type PutAuthByClientV1AccountEmailData = {
    body?: Email2;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/account/email';
};

export type PutAuthByClientV1AccountEmailErrors = {
    /**
     * An input error occurred.
     */
    400: ErrorResponse;
    /**
     * Too many email verification mails were already sent.
     *
     */
    403: ForbiddenResponse;
};

export type PutAuthByClientV1AccountEmailError = PutAuthByClientV1AccountEmailErrors[keyof PutAuthByClientV1AccountEmailErrors];

export type PutAuthByClientV1AccountEmailResponses = {
    /**
     * A success response.
     *
     */
    200: {
        status: StatusOk;
    };
};

export type PutAuthByClientV1AccountEmailResponse = PutAuthByClientV1AccountEmailResponses[keyof PutAuthByClientV1AccountEmailResponses];

export type PostAuthByClientV1AccountPasswordChangeData = {
    body?: ChangePassword;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/account/password/change';
};

export type PostAuthByClientV1AccountPasswordChangeErrors = {
    /**
     * An input error occurred.
     */
    400: ErrorResponse;
    /**
     * Not authenticated.
     */
    401: AuthenticationResponse;
};

export type PostAuthByClientV1AccountPasswordChangeError = PostAuthByClientV1AccountPasswordChangeErrors[keyof PostAuthByClientV1AccountPasswordChangeErrors];

export type GetAuthByClientV1AccountPhoneData = {
    body?: never;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/account/phone';
};

export type GetAuthByClientV1AccountPhoneErrors = {
    /**
     * Not authenticated.
     */
    401: AuthenticationResponse;
};

export type GetAuthByClientV1AccountPhoneError = GetAuthByClientV1AccountPhoneErrors[keyof GetAuthByClientV1AccountPhoneErrors];

export type GetAuthByClientV1AccountPhoneResponses = {
    /**
     * List of phone numbers.
     *
     */
    200: PhoneNumbersResponse;
};

export type GetAuthByClientV1AccountPhoneResponse = GetAuthByClientV1AccountPhoneResponses[keyof GetAuthByClientV1AccountPhoneResponses];

export type PostAuthByClientV1AccountPhoneData = {
    body?: Phone2;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/account/phone';
};

export type PostAuthByClientV1AccountPhoneErrors = {
    /**
     * An input error occurred.
     */
    400: ErrorResponse;
    /**
     * The response indicates authentication or re-authentication is required.
     *
     */
    401: AuthenticationResponse | ReauthenticationResponse;
    /**
     * Conflict. For example, when no user is authenticated and no phone verification flow is pending.
     *
     */
    409: ConflictResponse;
};

export type PostAuthByClientV1AccountPhoneError = PostAuthByClientV1AccountPhoneErrors[keyof PostAuthByClientV1AccountPhoneErrors];

export type PostAuthByClientV1AccountPhoneResponses = {
    /**
     * Phone number change process initiated.
     */
    202: PhoneNumberChangeResponse;
};

export type PostAuthByClientV1AccountPhoneResponse = PostAuthByClientV1AccountPhoneResponses[keyof PostAuthByClientV1AccountPhoneResponses];

export type DeleteAuthByClientV1AccountProvidersData = {
    body?: ProviderAccount2;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/account/providers';
};

export type DeleteAuthByClientV1AccountProvidersErrors = {
    /**
     * An input error occurred.
     */
    400: ErrorResponse;
};

export type DeleteAuthByClientV1AccountProvidersError = DeleteAuthByClientV1AccountProvidersErrors[keyof DeleteAuthByClientV1AccountProvidersErrors];

export type DeleteAuthByClientV1AccountProvidersResponses = {
    /**
     * List of third-party provider accounts.
     *
     */
    200: {
        data: Array<ProviderAccount>;
        status: StatusOk;
    };
};

export type DeleteAuthByClientV1AccountProvidersResponse = DeleteAuthByClientV1AccountProvidersResponses[keyof DeleteAuthByClientV1AccountProvidersResponses];

export type GetAuthByClientV1AccountProvidersData = {
    body?: never;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/account/providers';
};

export type GetAuthByClientV1AccountProvidersResponses = {
    /**
     * List of third-party provider accounts.
     *
     */
    200: {
        data: Array<ProviderAccount>;
        status: StatusOk;
    };
};

export type GetAuthByClientV1AccountProvidersResponse = GetAuthByClientV1AccountProvidersResponses[keyof GetAuthByClientV1AccountProvidersResponses];

export type PostAuthByClientV1Auth2FaAuthenticateData = {
    body: MfaAuthenticate2;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/auth/2fa/authenticate';
};

export type PostAuthByClientV1Auth2FaAuthenticateErrors = {
    /**
     * An input error occurred.
     */
    400: ErrorResponse;
    /**
     * Not authenticated.
     */
    401: AuthenticationResponse;
};

export type PostAuthByClientV1Auth2FaAuthenticateError = PostAuthByClientV1Auth2FaAuthenticateErrors[keyof PostAuthByClientV1Auth2FaAuthenticateErrors];

export type PostAuthByClientV1Auth2FaAuthenticateResponses = {
    /**
     * Authenticated by password and 2FA.
     *
     */
    200: AuthenticatedResponse;
};

export type PostAuthByClientV1Auth2FaAuthenticateResponse = PostAuthByClientV1Auth2FaAuthenticateResponses[keyof PostAuthByClientV1Auth2FaAuthenticateResponses];

export type PostAuthByClientV1Auth2FaReauthenticateData = {
    body: MfaAuthenticate2;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/auth/2fa/reauthenticate';
};

export type PostAuthByClientV1Auth2FaReauthenticateErrors = {
    /**
     * An input error occurred.
     */
    400: ErrorResponse;
};

export type PostAuthByClientV1Auth2FaReauthenticateError = PostAuthByClientV1Auth2FaReauthenticateErrors[keyof PostAuthByClientV1Auth2FaReauthenticateErrors];

export type PostAuthByClientV1Auth2FaReauthenticateResponses = {
    /**
     * Authenticated by password and 2FA.
     *
     */
    200: AuthenticatedResponse;
};

export type PostAuthByClientV1Auth2FaReauthenticateResponse = PostAuthByClientV1Auth2FaReauthenticateResponses[keyof PostAuthByClientV1Auth2FaReauthenticateResponses];

export type PostAuthByClientV1AuthCodeConfirmData = {
    body: ConfirmLoginCode2;
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/auth/code/confirm';
};

export type PostAuthByClientV1AuthCodeConfirmErrors = {
    /**
     * An input error occurred.
     */
    400: ErrorResponse;
    /**
     * Not authenticated.
     *
     */
    401: AuthenticationResponse;
    /**
     * Conflict. The "login by code" flow is not pending.
     *
     */
    409: ConflictResponse;
};

export type PostAuthByClientV1AuthCodeConfirmError = PostAuthByClientV1AuthCodeConfirmErrors[keyof PostAuthByClientV1AuthCodeConfirmErrors];

export type PostAuthByClientV1AuthCodeConfirmResponses = {
    /**
     * Authenticated by code.
     *
     */
    200: AuthenticatedResponse;
};

export type PostAuthByClientV1AuthCodeConfirmResponse = PostAuthByClientV1AuthCodeConfirmResponses[keyof PostAuthByClientV1AuthCodeConfirmResponses];

export type GetAuthByClientV1AuthEmailVerifyData = {
    body?: never;
    headers: {
        /**
         * The email verification key
         */
        'X-Email-Verification-Key': string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/auth/email/verify';
};

export type GetAuthByClientV1AuthEmailVerifyErrors = {
    /**
     * An input error occurred.
     *
     */
    400: ErrorResponse;
    /**
     * Conflict. The email verification (by code) flow is not pending.
     *
     */
    409: ConflictResponse;
};

export type GetAuthByClientV1AuthEmailVerifyError = GetAuthByClientV1AuthEmailVerifyErrors[keyof GetAuthByClientV1AuthEmailVerifyErrors];

export type GetAuthByClientV1AuthEmailVerifyResponses = {
    /**
     * Email verification information.
     */
    200: EmailVerificationInfo;
};

export type GetAuthByClientV1AuthEmailVerifyResponse = GetAuthByClientV1AuthEmailVerifyResponses[keyof GetAuthByClientV1AuthEmailVerifyResponses];

export type PostAuthByClientV1AuthEmailVerifyData = {
    body?: VerifyEmail2;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/auth/email/verify';
};

export type PostAuthByClientV1AuthEmailVerifyErrors = {
    /**
     * An input error occurred.
     *
     */
    400: ErrorResponse;
    /**
     * There is no authenticated session.
     *
     */
    401: AuthenticationResponse;
    /**
     * Conflict. The email verification (by code) flow is not pending.
     *
     */
    409: ConflictResponse;
};

export type PostAuthByClientV1AuthEmailVerifyError = PostAuthByClientV1AuthEmailVerifyErrors[keyof PostAuthByClientV1AuthEmailVerifyErrors];

export type PostAuthByClientV1AuthEmailVerifyResponses = {
    /**
     * The user is authenticated.
     */
    200: AuthenticatedResponse;
};

export type PostAuthByClientV1AuthEmailVerifyResponse = PostAuthByClientV1AuthEmailVerifyResponses[keyof PostAuthByClientV1AuthEmailVerifyResponses];

export type PostAuthByClientV1AuthEmailVerifyResendData = {
    body?: never;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/auth/email/verify/resend';
};

export type PostAuthByClientV1AuthEmailVerifyResendErrors = {
    /**
     * Conflict. The email verification (by code) flow is not pending.
     *
     */
    409: ConflictResponse;
    /**
     * Too many requests.
     *
     */
    429: {
        status: 429;
    };
};

export type PostAuthByClientV1AuthEmailVerifyResendError = PostAuthByClientV1AuthEmailVerifyResendErrors[keyof PostAuthByClientV1AuthEmailVerifyResendErrors];

export type PostAuthByClientV1AuthEmailVerifyResendResponses = {
    /**
     * A success response.
     *
     */
    200: {
        status: StatusOk;
    };
};

export type PostAuthByClientV1AuthEmailVerifyResendResponse = PostAuthByClientV1AuthEmailVerifyResendResponses[keyof PostAuthByClientV1AuthEmailVerifyResendResponses];

export type PostAuthByClientV1AuthLoginData = {
    /**
     * Login.
     */
    body: Login2;
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/auth/login';
};

export type PostAuthByClientV1AuthLoginErrors = {
    /**
     * An input error occurred.
     */
    400: ErrorResponse;
    /**
     * Not authenticated.
     *
     */
    401: AuthenticationResponse;
    /**
     * Conflict. For example, when logging in when a user is already logged in.
     *
     */
    409: ConflictResponse;
};

export type PostAuthByClientV1AuthLoginError = PostAuthByClientV1AuthLoginErrors[keyof PostAuthByClientV1AuthLoginErrors];

export type PostAuthByClientV1AuthLoginResponses = {
    /**
     * Authenticated by password.
     *
     */
    200: AuthenticatedResponse;
};

export type PostAuthByClientV1AuthLoginResponse = PostAuthByClientV1AuthLoginResponses[keyof PostAuthByClientV1AuthLoginResponses];

export type PostAuthByClientV1AuthPasswordRequestData = {
    /**
     * Request password.
     */
    body: RequestPassword2;
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/auth/password/request';
};

export type PostAuthByClientV1AuthPasswordRequestErrors = {
    /**
     * An input error occurred.
     *
     */
    400: ErrorResponse;
    /**
     * Not authenticated.
     */
    401: AuthenticationResponse;
};

export type PostAuthByClientV1AuthPasswordRequestError = PostAuthByClientV1AuthPasswordRequestErrors[keyof PostAuthByClientV1AuthPasswordRequestErrors];

export type PostAuthByClientV1AuthPasswordRequestResponses = {
    /**
     * A success response.
     *
     */
    200: {
        status: StatusOk;
    };
};

export type PostAuthByClientV1AuthPasswordRequestResponse = PostAuthByClientV1AuthPasswordRequestResponses[keyof PostAuthByClientV1AuthPasswordRequestResponses];

export type GetAuthByClientV1AuthPasswordResetData = {
    body?: never;
    headers: {
        /**
         * The password reset key
         */
        'X-Password-Reset-Key': string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/auth/password/reset';
};

export type GetAuthByClientV1AuthPasswordResetErrors = {
    /**
     * An input error occurred.
     *
     */
    400: ErrorResponse;
    /**
     * Conflict. There is no password reset (by code) flow pending.
     *
     */
    409: ConflictResponse;
};

export type GetAuthByClientV1AuthPasswordResetError = GetAuthByClientV1AuthPasswordResetErrors[keyof GetAuthByClientV1AuthPasswordResetErrors];

export type GetAuthByClientV1AuthPasswordResetResponses = {
    /**
     * Information about the password reset key.
     */
    200: {
        data: {
            user?: User;
        };
        status: StatusOk;
    };
};

export type GetAuthByClientV1AuthPasswordResetResponse = GetAuthByClientV1AuthPasswordResetResponses[keyof GetAuthByClientV1AuthPasswordResetResponses];

export type PostAuthByClientV1AuthPasswordResetData = {
    body?: ResetPassword2;
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/auth/password/reset';
};

export type PostAuthByClientV1AuthPasswordResetErrors = {
    /**
     * An input error occurred.
     */
    400: ErrorResponse;
    /**
     * Not authenticated.
     */
    401: AuthenticationResponse;
    /**
     * Conflict. There is no password reset (by code) flow pending.
     *
     */
    409: ConflictResponse;
};

export type PostAuthByClientV1AuthPasswordResetError = PostAuthByClientV1AuthPasswordResetErrors[keyof PostAuthByClientV1AuthPasswordResetErrors];

export type PostAuthByClientV1AuthPasswordResetResponses = {
    /**
     * Authenticated by password.
     *
     */
    200: AuthenticatedResponse;
};

export type PostAuthByClientV1AuthPasswordResetResponse = PostAuthByClientV1AuthPasswordResetResponses[keyof PostAuthByClientV1AuthPasswordResetResponses];

export type PostAuthByClientV1AuthPhoneVerifyData = {
    body?: VerifyPhone2;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/auth/phone/verify';
};

export type PostAuthByClientV1AuthPhoneVerifyErrors = {
    /**
     * An input error occurred.
     *
     */
    400: ErrorResponse;
    /**
     * There is no authenticated session.
     *
     */
    401: AuthenticationResponse;
    /**
     * Conflict. The phone verification flow is not pending.
     *
     */
    409: ConflictResponse;
};

export type PostAuthByClientV1AuthPhoneVerifyError = PostAuthByClientV1AuthPhoneVerifyErrors[keyof PostAuthByClientV1AuthPhoneVerifyErrors];

export type PostAuthByClientV1AuthPhoneVerifyResponses = {
    /**
     * The user is authenticated.
     */
    200: AuthenticatedResponse;
};

export type PostAuthByClientV1AuthPhoneVerifyResponse = PostAuthByClientV1AuthPhoneVerifyResponses[keyof PostAuthByClientV1AuthPhoneVerifyResponses];

export type PostAuthByClientV1AuthPhoneVerifyResendData = {
    body?: never;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/auth/phone/verify/resend';
};

export type PostAuthByClientV1AuthPhoneVerifyResendErrors = {
    /**
     * Conflict. The phone verification flow is not pending.
     *
     */
    409: ConflictResponse;
    /**
     * Too many requests.
     *
     */
    429: {
        status: 429;
    };
};

export type PostAuthByClientV1AuthPhoneVerifyResendError = PostAuthByClientV1AuthPhoneVerifyResendErrors[keyof PostAuthByClientV1AuthPhoneVerifyResendErrors];

export type PostAuthByClientV1AuthPhoneVerifyResendResponses = {
    /**
     * A success response.
     *
     */
    200: {
        status: StatusOk;
    };
};

export type PostAuthByClientV1AuthPhoneVerifyResendResponse = PostAuthByClientV1AuthPhoneVerifyResendResponses[keyof PostAuthByClientV1AuthPhoneVerifyResendResponses];

export type GetAuthByClientV1AuthProviderSignupData = {
    body?: never;
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/auth/provider/signup';
};

export type GetAuthByClientV1AuthProviderSignupErrors = {
    /**
     * Conflict. The provider signup flow is not pending.
     *
     */
    409: ConflictResponse;
};

export type GetAuthByClientV1AuthProviderSignupError = GetAuthByClientV1AuthProviderSignupErrors[keyof GetAuthByClientV1AuthProviderSignupErrors];

export type GetAuthByClientV1AuthProviderSignupResponses = {
    /**
     * Information relating to the pending provider signup.
     *
     */
    200: {
        data: {
            account: ProviderAccount;
            email: Array<EmailAddress>;
            user: User;
        };
        status: StatusOk;
    };
};

export type GetAuthByClientV1AuthProviderSignupResponse = GetAuthByClientV1AuthProviderSignupResponses[keyof GetAuthByClientV1AuthProviderSignupResponses];

export type PostAuthByClientV1AuthProviderSignupData = {
    /**
     * Provider signup.
     */
    body: ProviderSignup2;
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/auth/provider/signup';
};

export type PostAuthByClientV1AuthProviderSignupErrors = {
    /**
     * An input error occurred.
     */
    400: ErrorResponse;
    /**
     * Not authenticated, more steps are required to be completed.
     */
    401: AuthenticationResponse;
    /**
     * Forbidden. For example, when signup is closed.
     *
     */
    403: ForbiddenResponse;
    /**
     * Conflict. The provider signup flow is not pending.
     *
     */
    409: ConflictResponse;
};

export type PostAuthByClientV1AuthProviderSignupError = PostAuthByClientV1AuthProviderSignupErrors[keyof PostAuthByClientV1AuthProviderSignupErrors];

export type PostAuthByClientV1AuthProviderSignupResponses = {
    /**
     * The user is authenticated.
     */
    200: AuthenticatedResponse;
};

export type PostAuthByClientV1AuthProviderSignupResponse = PostAuthByClientV1AuthProviderSignupResponses[keyof PostAuthByClientV1AuthProviderSignupResponses];

export type PostAuthByClientV1AuthProviderTokenData = {
    body: ProviderToken2;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/auth/provider/token';
};

export type PostAuthByClientV1AuthProviderTokenErrors = {
    /**
     * An input error occurred.
     */
    400: ErrorResponse;
    /**
     * Not authenticated, more steps are required to be completed.
     */
    401: AuthenticationResponse;
    /**
     * Forbidden. For example, when signup is closed.
     *
     */
    403: ForbiddenResponse;
};

export type PostAuthByClientV1AuthProviderTokenError = PostAuthByClientV1AuthProviderTokenErrors[keyof PostAuthByClientV1AuthProviderTokenErrors];

export type PostAuthByClientV1AuthProviderTokenResponses = {
    /**
     * The user is authenticated.
     */
    200: AuthenticatedResponse;
};

export type PostAuthByClientV1AuthProviderTokenResponse = PostAuthByClientV1AuthProviderTokenResponses[keyof PostAuthByClientV1AuthProviderTokenResponses];

export type PostAuthByClientV1AuthReauthenticateData = {
    /**
     * Reauthenticate.
     */
    body: Reauthenticate2;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/auth/reauthenticate';
};

export type PostAuthByClientV1AuthReauthenticateErrors = {
    /**
     * An input error occurred.
     */
    400: ErrorResponse;
};

export type PostAuthByClientV1AuthReauthenticateError = PostAuthByClientV1AuthReauthenticateErrors[keyof PostAuthByClientV1AuthReauthenticateErrors];

export type PostAuthByClientV1AuthReauthenticateResponses = {
    /**
     * Authenticated by password.
     *
     */
    200: AuthenticatedResponse;
};

export type PostAuthByClientV1AuthReauthenticateResponse = PostAuthByClientV1AuthReauthenticateResponses[keyof PostAuthByClientV1AuthReauthenticateResponses];

export type DeleteAuthByClientV1AuthSessionData = {
    body?: never;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/auth/session';
};

export type DeleteAuthByClientV1AuthSessionErrors = {
    /**
     * There is no authenticated session.
     *
     */
    401: AuthenticationResponse;
};

export type DeleteAuthByClientV1AuthSessionError = DeleteAuthByClientV1AuthSessionErrors[keyof DeleteAuthByClientV1AuthSessionErrors];

export type GetAuthByClientV1AuthSessionData = {
    body?: never;
    headers?: {
        /**
         * Session token. Only needed when `client` is equal to `app`.
         *
         */
        'X-Session-Token'?: string;
    };
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/auth/session';
};

export type GetAuthByClientV1AuthSessionErrors = {
    /**
     * Not authenticated.
     */
    401: AuthenticationResponse;
    /**
     * The response indicates session is invalid or no longer exists.
     *
     */
    410: SessionGoneResponse;
};

export type GetAuthByClientV1AuthSessionError = GetAuthByClientV1AuthSessionErrors[keyof GetAuthByClientV1AuthSessionErrors];

export type GetAuthByClientV1AuthSessionResponses = {
    /**
     * The user is authenticated.
     */
    200: AuthenticatedResponse;
};

export type GetAuthByClientV1AuthSessionResponse = GetAuthByClientV1AuthSessionResponses[keyof GetAuthByClientV1AuthSessionResponses];

export type PostAuthByClientV1AuthSignupData = {
    /**
     * Signup
     */
    body: Signup2;
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/auth/signup';
};

export type PostAuthByClientV1AuthSignupErrors = {
    /**
     * An input error occurred.
     *
     */
    400: ErrorResponse;
    /**
     * Not authenticated.
     *
     */
    401: AuthenticationResponse;
    /**
     * Forbidden. For example, when signup is closed.
     *
     */
    403: ForbiddenResponse;
    /**
     * Conflict. For example, when signing up while user is logged in.
     *
     */
    409: ConflictResponse;
};

export type PostAuthByClientV1AuthSignupError = PostAuthByClientV1AuthSignupErrors[keyof PostAuthByClientV1AuthSignupErrors];

export type PostAuthByClientV1AuthSignupResponses = {
    /**
     * Authenticated by password.
     *
     */
    200: AuthenticatedResponse;
};

export type PostAuthByClientV1AuthSignupResponse = PostAuthByClientV1AuthSignupResponses[keyof PostAuthByClientV1AuthSignupResponses];

export type GetAuthByClientV1ConfigData = {
    body?: never;
    path: {
        /**
         * The type of client accessing the API.
         */
        client: 'app' | 'browser';
    };
    query?: never;
    url: '/auth/{client}/v1/config';
};

export type GetAuthByClientV1ConfigResponses = {
    /**
     * The django-allauth configuration.
     *
     */
    200: ConfigurationResponse;
};

export type GetAuthByClientV1ConfigResponse = GetAuthByClientV1ConfigResponses[keyof GetAuthByClientV1ConfigResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};