// This file is auto-generated by @hey-api/openapi-ts

export type AvailableTimeWindow = {
    id: number;
    start_time: string;
    end_time: string;
    can_book_partially: boolean;
};

/**
 * Serializer for BillingAddress virtual model.
 */
export type BillingAddress = {
    readonly id: number;
    street_name: string;
    street_number: string;
    neighborhood?: string;
    address_line_2?: string;
    city: string;
    state: string;
    country: string;
    zip_code: string;
};

/**
 * Serializer for BillingProfile virtual model.
 */
export type BillingProfile = {
    readonly id: number;
    document_type: string;
    document_number: string;
    billing_address: BillingAddress;
    readonly created: string;
    readonly modified: string;
};

export type CalendarEvent = {
    readonly id: number;
    title: string;
    description?: string;
    start_time: string;
    end_time: string;
    readonly created: string;
    readonly modified: string;
    readonly external_id: string;
    external_attendances: Array<EventExternalAttendance>;
    attendances: Array<EventAttendance>;
    resource_allocations: Array<ResourceAllocation>;
    recurrence_rule: RecurrenceRule;
    parent_event: ParentEvent;
    /**
     * True if this is an instance of a recurring event
     */
    readonly is_recurring_instance: boolean;
    /**
     * True if this is a recurring event
     */
    readonly is_recurring: boolean;
    /**
     * True if this event is an exception to the recurrence rule (modified occurrence)
     */
    is_recurring_exception?: boolean;
    /**
     * For recurring event instances, this identifies which occurrence this is
     */
    recurrence_id?: string | null;
};

export type EventAttendance = {
    /**
     * ID of the external attendee.
     */
    id?: number | null;
    user: User;
    status: StatusEnum;
    readonly created: string;
    readonly modified: string;
};

export type EventExternalAttendance = {
    /**
     * ID of the external attendee.
     */
    id?: number | null;
    external_attendee: ExternalAttendee;
    status: StatusEnum;
    readonly created: string;
    readonly modified: string;
};

export type ExternalAttendee = {
    /**
     * ID of the external attendee.
     */
    id?: number | null;
    name?: string;
    email: string;
    readonly created: string;
    readonly modified: string;
};

/**
 * * `DAILY` - Daily
 * * `WEEKLY` - Weekly
 * * `MONTHLY` - Monthly
 * * `YEARLY` - Yearly
 */
export type FrequencyEnum = 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY';

export type PaginatedAvailableTimeWindowList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AvailableTimeWindow>;
};

export type PaginatedCalendarEventList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<CalendarEvent>;
};

export type PaginatedUnavailableTimeWindowList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<UnavailableTimeWindow>;
};

export type ParentEvent = {
    readonly id: number;
    title: string;
    readonly external_id: string;
    start_time: string;
    end_time: string;
    readonly created: string;
    readonly modified: string;
};

/**
 * Serializer for BillingProfile virtual model.
 */
export type PatchedBillingProfile = {
    readonly id?: number;
    document_type?: string;
    document_number?: string;
    billing_address?: BillingAddress;
    readonly created?: string;
    readonly modified?: string;
};

export type PatchedCalendarEvent = {
    readonly id?: number;
    title?: string;
    description?: string;
    start_time?: string;
    end_time?: string;
    readonly created?: string;
    readonly modified?: string;
    readonly external_id?: string;
    external_attendances?: Array<EventExternalAttendance>;
    attendances?: Array<EventAttendance>;
    resource_allocations?: Array<ResourceAllocation>;
    recurrence_rule?: RecurrenceRule;
    parent_event?: ParentEvent;
    /**
     * True if this is an instance of a recurring event
     */
    readonly is_recurring_instance?: boolean;
    /**
     * True if this is a recurring event
     */
    readonly is_recurring?: boolean;
    /**
     * True if this event is an exception to the recurrence rule (modified occurrence)
     */
    is_recurring_exception?: boolean;
    /**
     * For recurring event instances, this identifies which occurrence this is
     */
    recurrence_id?: string | null;
};

export type PatchedProfile = {
    readonly id?: number;
    first_name?: string;
    last_name?: string;
    profile_picture?: string | null;
};

export type Profile = {
    readonly id: number;
    first_name?: string;
    last_name?: string;
    profile_picture?: string | null;
};

export type RecurrenceRule = {
    readonly id: number;
    /**
     * How often the event repeats (DAILY, WEEKLY, MONTHLY, YEARLY)
     *
     * * `DAILY` - Daily
     * * `WEEKLY` - Weekly
     * * `MONTHLY` - Monthly
     * * `YEARLY` - Yearly
     */
    frequency: FrequencyEnum;
    /**
     * The interval between each frequency iteration (e.g., every 2 weeks)
     */
    interval?: number;
    /**
     * Number of occurrences after which the recurrence ends
     */
    count?: number | null;
    /**
     * The date and time until which the recurrence is valid
     */
    until?: string | null;
    /**
     * Comma-separated list of weekdays (e.g., 'MO,WE,FR')
     */
    by_weekday?: string;
    /**
     * Comma-separated list of month days (e.g., '1,15,-1' for 1st, 15th, last day)
     */
    by_month_day?: string;
    /**
     * Comma-separated list of months (1-12)
     */
    by_month?: string;
    /**
     * Comma-separated list of year days (1-366 or -366 to -1)
     */
    by_year_day?: string;
    /**
     * Comma-separated list of week numbers (1-53 or -53 to -1)
     */
    by_week_number?: string;
    /**
     * Comma-separated list of hours (0-23)
     */
    by_hour?: string;
    /**
     * Comma-separated list of minutes (0-59)
     */
    by_minute?: string;
    /**
     * Comma-separated list of seconds (0-59)
     */
    by_second?: string;
    /**
     * First day of the week
     *
     * * `MO` - Monday
     * * `TU` - Tuesday
     * * `WE` - Wednesday
     * * `TH` - Thursday
     * * `FR` - Friday
     * * `SA` - Saturday
     * * `SU` - Sunday
     */
    week_start?: WeekStartEnum;
    readonly rrule_string: string;
    readonly created: string;
    readonly modified: string;
};

export type ResourceAllocation = {
    /**
     * ID of the external attendee.
     */
    id?: number | null;
    calendar: number;
    status: StatusEnum;
    readonly created: string;
    readonly modified: string;
};

/**
 * * `accepted` - Accepted
 * * `declined` - Declined
 * * `pending` - Pending
 */
export type StatusEnum = 'accepted' | 'declined' | 'pending';

export type UnavailableTimeWindow = {
    id: number;
    reason: string;
    start_time: string;
    end_time: string;
    readonly reason_description: string;
};

export type User = {
    readonly id: number;
    readonly email: string;
    readonly phone_number: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    profile: Profile;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    readonly is_active: boolean;
    /**
     * Designates whether the user can log into this admin site.
     */
    readonly is_staff: boolean;
    /**
     * Superuser status
     * Designates that this user has all permissions without explicitly assigning them.
     */
    readonly is_superuser: boolean;
    readonly created: string;
    readonly modified: string;
    readonly last_login: string | null;
};

/**
 * * `MO` - Monday
 * * `TU` - Tuesday
 * * `WE` - Wednesday
 * * `TH` - Thursday
 * * `FR` - Friday
 * * `SA` - Saturday
 * * `SU` - Sunday
 */
export type WeekStartEnum = 'MO' | 'TU' | 'WE' | 'TH' | 'FR' | 'SA' | 'SU';

export type CalendarEventWritable = {
    provider?: string;
    title: string;
    description?: string;
    start_time: string;
    end_time: string;
    external_attendances: Array<EventExternalAttendance>;
    attendances: Array<EventAttendanceWritable>;
    resource_allocations: Array<ResourceAllocation>;
    /**
     * Recurrence rule data for creating recurring events
     */
    recurrence_rule_data?: RecurrenceRule;
    /**
     * RRULE string for creating recurring events
     */
    rrule_string?: string;
    /**
     * ID of parent event for recurring instances
     */
    parent_event_id?: number;
    /**
     * True if this event is an exception to the recurrence rule (modified occurrence)
     */
    is_recurring_exception?: boolean;
    /**
     * For recurring event instances, this identifies which occurrence this is
     */
    recurrence_id?: string | null;
    google_calendar_service_account?: number;
    calendar?: number;
};

export type EventAttendanceWritable = {
    /**
     * ID of the external attendee.
     */
    id?: number | null;
    user_id: number;
};

/**
 * * `DAILY` - Daily
 * * `WEEKLY` - Weekly
 * * `MONTHLY` - Monthly
 * * `YEARLY` - Yearly
 */
export type FrequencyEnumWritable = 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY';

export type PaginatedCalendarEventListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<CalendarEventWritable>;
};

export type PatchedCalendarEventWritable = {
    provider?: string;
    title?: string;
    description?: string;
    start_time?: string;
    end_time?: string;
    external_attendances?: Array<EventExternalAttendance>;
    attendances?: Array<EventAttendanceWritable>;
    resource_allocations?: Array<ResourceAllocation>;
    /**
     * Recurrence rule data for creating recurring events
     */
    recurrence_rule_data?: RecurrenceRule;
    /**
     * RRULE string for creating recurring events
     */
    rrule_string?: string;
    /**
     * ID of parent event for recurring instances
     */
    parent_event_id?: number;
    /**
     * True if this event is an exception to the recurrence rule (modified occurrence)
     */
    is_recurring_exception?: boolean;
    /**
     * For recurring event instances, this identifies which occurrence this is
     */
    recurrence_id?: string | null;
    google_calendar_service_account?: number;
    calendar?: number;
};

/**
 * * `accepted` - Accepted
 * * `declined` - Declined
 * * `pending` - Pending
 */
export type StatusEnumWritable = 'accepted' | 'declined' | 'pending';

/**
 * * `MO` - Monday
 * * `TU` - Tuesday
 * * `WE` - Wednesday
 * * `TH` - Thursday
 * * `FR` - Friday
 * * `SA` - Saturday
 * * `SU` - Sunday
 */
export type WeekStartEnumWritable = 'MO' | 'TU' | 'WE' | 'TH' | 'FR' | 'SA' | 'SU';

export type BillingProfileCreateBillingProfileCreateData = {
    body: BillingProfile;
    path?: never;
    query?: never;
    url: '/billing-profile/create_billing_profile/';
};

export type BillingProfileCreateBillingProfileCreateResponses = {
    201: BillingProfile;
};

export type BillingProfileCreateBillingProfileCreateResponse = BillingProfileCreateBillingProfileCreateResponses[keyof BillingProfileCreateBillingProfileCreateResponses];

export type BillingProfileCreateBillingProfileFormattedCreateData = {
    body: BillingProfile;
    path: {
        format: '.json';
    };
    query?: never;
    url: '/billing-profile/create_billing_profile{format}';
};

export type BillingProfileCreateBillingProfileFormattedCreateResponses = {
    201: BillingProfile;
};

export type BillingProfileCreateBillingProfileFormattedCreateResponse = BillingProfileCreateBillingProfileFormattedCreateResponses[keyof BillingProfileCreateBillingProfileFormattedCreateResponses];

export type BillingProfilePartialUpdateBillingProfilePartialUpdateData = {
    body?: PatchedBillingProfile;
    path?: never;
    query?: never;
    url: '/billing-profile/partial_update_billing_profile/';
};

export type BillingProfilePartialUpdateBillingProfilePartialUpdateResponses = {
    200: BillingProfile;
};

export type BillingProfilePartialUpdateBillingProfilePartialUpdateResponse = BillingProfilePartialUpdateBillingProfilePartialUpdateResponses[keyof BillingProfilePartialUpdateBillingProfilePartialUpdateResponses];

export type BillingProfilePartialUpdateBillingProfileFormattedPartialUpdateData = {
    body?: PatchedBillingProfile;
    path: {
        format: '.json';
    };
    query?: never;
    url: '/billing-profile/partial_update_billing_profile{format}';
};

export type BillingProfilePartialUpdateBillingProfileFormattedPartialUpdateResponses = {
    200: BillingProfile;
};

export type BillingProfilePartialUpdateBillingProfileFormattedPartialUpdateResponse = BillingProfilePartialUpdateBillingProfileFormattedPartialUpdateResponses[keyof BillingProfilePartialUpdateBillingProfileFormattedPartialUpdateResponses];

export type BillingProfileRetrieveBillingProfileRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/billing-profile/retrieve_billing_profile/';
};

export type BillingProfileRetrieveBillingProfileRetrieveResponses = {
    200: BillingProfile;
};

export type BillingProfileRetrieveBillingProfileRetrieveResponse = BillingProfileRetrieveBillingProfileRetrieveResponses[keyof BillingProfileRetrieveBillingProfileRetrieveResponses];

export type BillingProfileRetrieveBillingProfileFormattedRetrieveData = {
    body?: never;
    path: {
        format: '.json';
    };
    query?: never;
    url: '/billing-profile/retrieve_billing_profile{format}';
};

export type BillingProfileRetrieveBillingProfileFormattedRetrieveResponses = {
    200: BillingProfile;
};

export type BillingProfileRetrieveBillingProfileFormattedRetrieveResponse = BillingProfileRetrieveBillingProfileFormattedRetrieveResponses[keyof BillingProfileRetrieveBillingProfileFormattedRetrieveResponses];

export type BillingProfileUpdateBillingProfileUpdateData = {
    body: BillingProfile;
    path?: never;
    query?: never;
    url: '/billing-profile/update_billing_profile/';
};

export type BillingProfileUpdateBillingProfileUpdateResponses = {
    200: BillingProfile;
};

export type BillingProfileUpdateBillingProfileUpdateResponse = BillingProfileUpdateBillingProfileUpdateResponses[keyof BillingProfileUpdateBillingProfileUpdateResponses];

export type BillingProfileUpdateBillingProfileFormattedUpdateData = {
    body: BillingProfile;
    path: {
        format: '.json';
    };
    query?: never;
    url: '/billing-profile/update_billing_profile{format}';
};

export type BillingProfileUpdateBillingProfileFormattedUpdateResponses = {
    200: BillingProfile;
};

export type BillingProfileUpdateBillingProfileFormattedUpdateResponse = BillingProfileUpdateBillingProfileFormattedUpdateResponses[keyof BillingProfileUpdateBillingProfileFormattedUpdateResponses];

export type CalendarEventsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by calendar ID
         */
        calendar?: number;
        /**
         * End time (less than or equal to)
         */
        end_time?: string;
        /**
         * End time range
         */
        end_time_range_after?: string;
        /**
         * End time range
         */
        end_time_range_before?: string;
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        /**
         * Start time (greater than or equal to)
         */
        start_time?: string;
        /**
         * Start time range
         */
        start_time_range_after?: string;
        /**
         * Start time range
         */
        start_time_range_before?: string;
        /**
         * Filter by partial title match
         */
        title?: string;
    };
    url: '/calendar-events/';
};

export type CalendarEventsListResponses = {
    200: PaginatedCalendarEventList;
};

export type CalendarEventsListResponse = CalendarEventsListResponses[keyof CalendarEventsListResponses];

export type CalendarEventsCreateData = {
    body: CalendarEventWritable;
    path?: never;
    query?: never;
    url: '/calendar-events/';
};

export type CalendarEventsCreateResponses = {
    201: CalendarEvent;
};

export type CalendarEventsCreateResponse = CalendarEventsCreateResponses[keyof CalendarEventsCreateResponses];

export type CalendarEventsFormattedListData = {
    body?: never;
    path: {
        format: '.json';
    };
    query?: {
        /**
         * Filter by calendar ID
         */
        calendar?: number;
        /**
         * End time (less than or equal to)
         */
        end_time?: string;
        /**
         * End time range
         */
        end_time_range_after?: string;
        /**
         * End time range
         */
        end_time_range_before?: string;
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        /**
         * Start time (greater than or equal to)
         */
        start_time?: string;
        /**
         * Start time range
         */
        start_time_range_after?: string;
        /**
         * Start time range
         */
        start_time_range_before?: string;
        /**
         * Filter by partial title match
         */
        title?: string;
    };
    url: '/calendar-events{format}';
};

export type CalendarEventsFormattedListResponses = {
    200: PaginatedCalendarEventList;
};

export type CalendarEventsFormattedListResponse = CalendarEventsFormattedListResponses[keyof CalendarEventsFormattedListResponses];

export type CalendarEventsFormattedCreateData = {
    body: CalendarEventWritable;
    path: {
        format: '.json';
    };
    query?: never;
    url: '/calendar-events{format}';
};

export type CalendarEventsFormattedCreateResponses = {
    201: CalendarEvent;
};

export type CalendarEventsFormattedCreateResponse = CalendarEventsFormattedCreateResponses[keyof CalendarEventsFormattedCreateResponses];

export type CalendarEventsDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/calendar-events/{id}/';
};

export type CalendarEventsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CalendarEventsDestroyResponse = CalendarEventsDestroyResponses[keyof CalendarEventsDestroyResponses];

export type CalendarEventsRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/calendar-events/{id}/';
};

export type CalendarEventsRetrieveResponses = {
    200: CalendarEvent;
};

export type CalendarEventsRetrieveResponse = CalendarEventsRetrieveResponses[keyof CalendarEventsRetrieveResponses];

export type CalendarEventsPartialUpdateData = {
    body?: PatchedCalendarEventWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/calendar-events/{id}/';
};

export type CalendarEventsPartialUpdateResponses = {
    200: CalendarEvent;
};

export type CalendarEventsPartialUpdateResponse = CalendarEventsPartialUpdateResponses[keyof CalendarEventsPartialUpdateResponses];

export type CalendarEventsUpdateData = {
    body: CalendarEventWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/calendar-events/{id}/';
};

export type CalendarEventsUpdateResponses = {
    200: CalendarEvent;
};

export type CalendarEventsUpdateResponse = CalendarEventsUpdateResponses[keyof CalendarEventsUpdateResponses];

export type CalendarEventsFormattedDestroyData = {
    body?: never;
    path: {
        format: '.json';
        id: string;
    };
    query?: never;
    url: '/calendar-events/{id}{format}';
};

export type CalendarEventsFormattedDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CalendarEventsFormattedDestroyResponse = CalendarEventsFormattedDestroyResponses[keyof CalendarEventsFormattedDestroyResponses];

export type CalendarEventsFormattedRetrieveData = {
    body?: never;
    path: {
        format: '.json';
        id: string;
    };
    query?: never;
    url: '/calendar-events/{id}{format}';
};

export type CalendarEventsFormattedRetrieveResponses = {
    200: CalendarEvent;
};

export type CalendarEventsFormattedRetrieveResponse = CalendarEventsFormattedRetrieveResponses[keyof CalendarEventsFormattedRetrieveResponses];

export type CalendarEventsFormattedPartialUpdateData = {
    body?: PatchedCalendarEventWritable;
    path: {
        format: '.json';
        id: string;
    };
    query?: never;
    url: '/calendar-events/{id}{format}';
};

export type CalendarEventsFormattedPartialUpdateResponses = {
    200: CalendarEvent;
};

export type CalendarEventsFormattedPartialUpdateResponse = CalendarEventsFormattedPartialUpdateResponses[keyof CalendarEventsFormattedPartialUpdateResponses];

export type CalendarEventsFormattedUpdateData = {
    body: CalendarEventWritable;
    path: {
        format: '.json';
        id: string;
    };
    query?: never;
    url: '/calendar-events/{id}{format}';
};

export type CalendarEventsFormattedUpdateResponses = {
    200: CalendarEvent;
};

export type CalendarEventsFormattedUpdateResponse = CalendarEventsFormattedUpdateResponses[keyof CalendarEventsFormattedUpdateResponses];

export type CalendarsAvailableWindowsListData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        /**
         * End datetime in ISO format (YYYY-MM-DDTHH:MM:SS)
         */
        end_datetime: string;
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        /**
         * Start datetime in ISO format (YYYY-MM-DDTHH:MM:SS)
         */
        start_datetime: string;
    };
    url: '/calendars/{id}/available-windows/';
};

export type CalendarsAvailableWindowsListResponses = {
    200: PaginatedAvailableTimeWindowList;
};

export type CalendarsAvailableWindowsListResponse = CalendarsAvailableWindowsListResponses[keyof CalendarsAvailableWindowsListResponses];

export type CalendarsAvailableWindowsFormattedListData = {
    body?: never;
    path: {
        format: '.json';
        id: string;
    };
    query: {
        /**
         * End datetime in ISO format (YYYY-MM-DDTHH:MM:SS)
         */
        end_datetime: string;
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        /**
         * Start datetime in ISO format (YYYY-MM-DDTHH:MM:SS)
         */
        start_datetime: string;
    };
    url: '/calendars/{id}/available-windows{format}';
};

export type CalendarsAvailableWindowsFormattedListResponses = {
    200: PaginatedAvailableTimeWindowList;
};

export type CalendarsAvailableWindowsFormattedListResponse = CalendarsAvailableWindowsFormattedListResponses[keyof CalendarsAvailableWindowsFormattedListResponses];

export type CalendarsUnavailableWindowsListData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        /**
         * End datetime in ISO format (YYYY-MM-DDTHH:MM:SS)
         */
        end_datetime: string;
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        /**
         * Start datetime in ISO format (YYYY-MM-DDTHH:MM:SS)
         */
        start_datetime: string;
    };
    url: '/calendars/{id}/unavailable-windows/';
};

export type CalendarsUnavailableWindowsListResponses = {
    200: PaginatedUnavailableTimeWindowList;
};

export type CalendarsUnavailableWindowsListResponse = CalendarsUnavailableWindowsListResponses[keyof CalendarsUnavailableWindowsListResponses];

export type CalendarsUnavailableWindowsFormattedListData = {
    body?: never;
    path: {
        format: '.json';
        id: string;
    };
    query: {
        /**
         * End datetime in ISO format (YYYY-MM-DDTHH:MM:SS)
         */
        end_datetime: string;
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        /**
         * Start datetime in ISO format (YYYY-MM-DDTHH:MM:SS)
         */
        start_datetime: string;
    };
    url: '/calendars/{id}/unavailable-windows{format}';
};

export type CalendarsUnavailableWindowsFormattedListResponses = {
    200: PaginatedUnavailableTimeWindowList;
};

export type CalendarsUnavailableWindowsFormattedListResponse = CalendarsUnavailableWindowsFormattedListResponses[keyof CalendarsUnavailableWindowsFormattedListResponses];

export type PaymentsPaymentUpdateCreateData = {
    body?: never;
    path: {
        id: string;
        provider: string;
    };
    query?: never;
    url: '/payments/{id}/payment-update/{provider}/';
};

export type PaymentsPaymentUpdateCreateResponses = {
    /**
     * Payment update received.
     */
    200: unknown;
};

export type PaymentsPaymentUpdateFormattedCreateData = {
    body?: never;
    path: {
        format: '.json';
        id: string;
        provider: string;
    };
    query?: never;
    url: '/payments/{id}/payment-update/{provider}{format}';
};

export type PaymentsPaymentUpdateFormattedCreateResponses = {
    /**
     * Payment update received.
     */
    200: unknown;
};

export type PaymentsSubscriptionPaymentUpdateCreateData = {
    body?: never;
    path: {
        id: string;
        provider: string;
    };
    query?: never;
    url: '/payments/{id}/subscription-payment-update/{provider}/';
};

export type PaymentsSubscriptionPaymentUpdateCreateResponses = {
    /**
     * Subscription payment update received.
     */
    200: unknown;
};

export type PaymentsSubscriptionPaymentUpdateFormattedCreateData = {
    body?: never;
    path: {
        format: '.json';
        id: string;
        provider: string;
    };
    query?: never;
    url: '/payments/{id}/subscription-payment-update/{provider}{format}';
};

export type PaymentsSubscriptionPaymentUpdateFormattedCreateResponses = {
    /**
     * Subscription payment update received.
     */
    200: unknown;
};

export type ProfileRetrieveData = {
    body?: never;
    path: {
        /**
         * User ID to retrieve or update the profile. Use 'me' to refer to the currently authenticated user.
         */
        user: string;
    };
    query?: never;
    url: '/profile/{user}/';
};

export type ProfileRetrieveResponses = {
    200: Profile;
};

export type ProfileRetrieveResponse = ProfileRetrieveResponses[keyof ProfileRetrieveResponses];

export type ProfilePartialUpdateData = {
    body?: PatchedProfile;
    path: {
        /**
         * User ID to update the profile. Use 'me' to refer to the currently authenticated user.
         */
        user: string;
    };
    query?: never;
    url: '/profile/{user}/';
};

export type ProfilePartialUpdateResponses = {
    200: Profile;
};

export type ProfilePartialUpdateResponse = ProfilePartialUpdateResponses[keyof ProfilePartialUpdateResponses];

export type ProfileUpdateData = {
    body?: Profile;
    path: {
        /**
         * User ID to update the profile. Use 'me' to refer to the currently authenticated user.
         */
        user: string;
    };
    query?: never;
    url: '/profile/{user}/';
};

export type ProfileUpdateResponses = {
    200: Profile;
};

export type ProfileUpdateResponse = ProfileUpdateResponses[keyof ProfileUpdateResponses];

export type ProfileFormattedRetrieveData = {
    body?: never;
    path: {
        format: '.json';
        /**
         * User ID to retrieve or update the profile. Use 'me' to refer to the currently authenticated user.
         */
        user: string;
    };
    query?: never;
    url: '/profile/{user}{format}';
};

export type ProfileFormattedRetrieveResponses = {
    200: Profile;
};

export type ProfileFormattedRetrieveResponse = ProfileFormattedRetrieveResponses[keyof ProfileFormattedRetrieveResponses];

export type ProfileFormattedPartialUpdateData = {
    body?: PatchedProfile;
    path: {
        format: '.json';
        /**
         * User ID to update the profile. Use 'me' to refer to the currently authenticated user.
         */
        user: string;
    };
    query?: never;
    url: '/profile/{user}{format}';
};

export type ProfileFormattedPartialUpdateResponses = {
    200: Profile;
};

export type ProfileFormattedPartialUpdateResponse = ProfileFormattedPartialUpdateResponses[keyof ProfileFormattedPartialUpdateResponses];

export type ProfileFormattedUpdateData = {
    body?: Profile;
    path: {
        format: '.json';
        /**
         * User ID to update the profile. Use 'me' to refer to the currently authenticated user.
         */
        user: string;
    };
    query?: never;
    url: '/profile/{user}{format}';
};

export type ProfileFormattedUpdateResponses = {
    200: Profile;
};

export type ProfileFormattedUpdateResponse = ProfileFormattedUpdateResponses[keyof ProfileFormattedUpdateResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};